In [54]:
import numpy as np
import pandas as pd
import random
import math
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.cross_validation import cross_val_score, train_test_split, KFold
from sklearn import metrics, preprocessing
import json
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

In [3]:
film = pd.read_csv("tmdb.csv")
film.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
print("Jumlah row pada data: {}".format(film.shape[0]))
print("Jumlah feature pada data: {}".format(film.shape[1]))

Jumlah row pada data: 4803
Jumlah feature pada data: 20

In [5]:
film.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [6]:
film.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [7]:
film['runtime'].fillna(float(film['runtime'].mean()), inplace = True)

In [8]:
film['runtime']

0       162.0
1       169.0
2       148.0
3       165.0
4       132.0
5       139.0
6       100.0
7       141.0
8       153.0
9       151.0
10      154.0
11      106.0
12      151.0
13      149.0
14      143.0
15      150.0
16      143.0
17      136.0
18      106.0
19      144.0
20      136.0
21      140.0
22      161.0
23      113.0
24      187.0
25      194.0
26      147.0
27      131.0
28      124.0
29      143.0
        ...
4773     92.0
4774     64.0
4775     85.0
4776     97.0
4777     78.0
4778     85.0
4779     97.0
4780     90.0
4781     90.0
4782    120.0
4783     91.0
4784     85.0
4785     60.0
4786     88.0
4787     78.0
4788     93.0
4789    111.0
4790     90.0
4791     84.0
4792    111.0
4793     90.0
4794     82.0
4795     98.0
4796     77.0
4797     80.0
4798     81.0
4799     85.0
4800    120.0
4801     98.0
4802     90.0
Name: runtime, dtype: float64

In [9]:
mode = film['tagline'].mode()
film['tagline'].fillna(str(mode), inplace = True)

In [10]:
film['release_date'].fillna('2006-01-01' ,inplace=True)
# film['release_date'].mode()

In [11]:
film['homepage'].fillna('missing homepage', inplace=True)

In [12]:
film['overview'].fillna('missing overview', inplace = True)

In [13]:
film.isnull().sum()

budget                  0
genres                  0
homepage                0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
tagline                 0
title                   0
vote_average            0
vote_count              0
dtype: int64

In [14]:
company = film['production_companies']
genre = film['genres']
prod_country = film['production_countries']

film = film.drop("homepage",1)
film = film.drop("keywords",1)
film = film.drop("original_language",1)
film = film.drop("original_title",1)
film = film.drop("overview",1)
film = film.drop("release_date",1)
film = film.drop("tagline",1)
film = film.drop("title",1)

ls = []
for i in company:
    v = json.loads(i)
    if len(v) != 0:
        ls.append(v[0].get('name'))
    else:
        ls.append('None')

film['production_companies'] = ls

ls = []
for i in genre:
    v = json.loads(i)
    if len(v) != 0:
        ls.append(v[0].get('name'))
    else:
        ls.append('None')

film['genres'] = ls

ls = []
for i in prod_country:
    v = json.loads(i)
    if len(v) != 0:
        ls.append(v[0].get('name'))
    else:
        ls.append('None')

film['production_countries'] = ls

In [15]:
film.head()

,budget,genres,id,popularity,production_companies,production_countries,revenue,runtime,spoken_languages,status,vote_average,vote_count
0,237000000,Action,19995,150.437577,Ingenious Film Partners,United States of America,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,7.2,11800
1,300000000,Adventure,285,139.082615,Walt Disney Pictures,United States of America,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,6.9,4500
2,245000000,Action,206647,107.376788,Columbia Pictures,United Kingdom,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,6.3,4466
3,250000000,Action,49026,112.312950,Legendary Pictures,United States of America,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,7.6,9106
4,260000000,Action,49529,43.926995,Walt Disney Pictures,United States of America,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,6.1,2124

In [16]:
spoken = film['spoken_languages']

ls = []
for i in spoken:
    v = json.loads(i)
    if len(v) != 0:
        ls.append(v[0].get('name'))
    else:
        ls.append('None')

film['spoken_languages'] = ls

In [17]:
film.head()

,budget,genres,id,popularity,production_companies,production_countries,revenue,runtime,spoken_languages,status,vote_average,vote_count
0,237000000,Action,19995,150.437577,Ingenious Film Partners,United States of America,2787965087,162.0,English,Released,7.2,11800
1,300000000,Adventure,285,139.082615,Walt Disney Pictures,United States of America,961000000,169.0,English,Released,6.9,4500
2,245000000,Action,206647,107.376788,Columbia Pictures,United Kingdom,880674609,148.0,Français,Released,6.3,4466
3,250000000,Action,49026,112.312950,Legendary Pictures,United States of America,1084939099,165.0,English,Released,7.6,9106
4,260000000,Action,49529,43.926995,Walt Disney Pictures,United States of America,284139100,132.0,English,Released,6.1,2124

In [18]:
film.corr(method='pearson').style.format("{:.2}").background_gradient(cmap=plt.get_cmap('coolwarm'), axis=1)

In [19]:
film.corr(method='spearman').style.format("{:.2}").background_gradient(cmap=plt.get_cmap('coolwarm'), axis=1)

In [20]:
# for i in film['production_companies']:
#     prod_name = set(i)
prod_name = set(film['production_companies'])

In [21]:
print(prod_name)

{'Anima Estudios', 'Carousel Picture Company, The', 'Tea Shop & Film Company', 'Eficine 226', 'Semi-Professional', 'Rainsworth Productions', 'Spring Creek Productions', 'Good Dick', 'Filmways Pictures', 'Section Eight', 'EMI Films', 'Code Entertainment', 'Patriot Pictures', 'Trust the Man LLC', 'Avon Production', 'Taewon Entertainment', 'Type A Films', 'Veracity Productions', '1492 Pictures', 'Cheap and Dirty Productions Inc.', '3D Entertainment', 'Gateway Films', 'New Line Cinema', 'World 2000 Entertainment', 'Instinctive Film', 'Imagine Entertainment', 'Aramid Entertainment Fund', 'Polygon Entertainment', 'Rhino Films', 'Tiny Ponies', '19 Entertainment', 'Cloud Eight Films', 'Winkler Films', 'Visualizer Film Productions', 'Dry County Films', 'Renn Productions', 'Atlas 3 Productions', 'Dreamland Productions', 'Senator Film Produktion', 'Havoc', 'Cimarron Productions', 'Vox3 Films', 'Filmazure', 'Fuller Films', 'AdScott Pictures', 'Allagash Films', 'Gener8Xion Entertainment', 'British Screen', 'Big Easy Pictures', 'Blue Sky Studios', 'Python (Monty) Pictures Limited', 'rusty bear entertainment', 'Lost Rhino Films', 'Spyglass Entertainment', 'Unified Pictures', 'Duck Farm Films', 'Handmade Films Ltd.', 'Avenue Pictures Productions', 'No Matter Pictures', 'Cube Vision', 'Wonderland Sound and Vision', 'AST Studios', 'Revolution Films', 'Red Envelope Entertainment', 'Cold Iron Pictures', 'Central-Europa Film', 'C&P Productions', 'Odd Lot Entertainment', 'Daiei Studios', 'Fortress Features', 'Penn Station Entertainment', 'Happy Madison Productions', 'Vía Digital', 'icon', '3Mark Entertainment', 'Melvin Simon Productions', 'Industrial House Films', 'Dan Films', 'MovieRoom Productions', 'Zelko Films', 'HanWay Films', 'Forensic Films', 'Lucky Coffee Productions', 'Grosvenor Park Media Ltd.', 'An Olive Branch Productions', 'Caviar Films', 'Canadian Broadcasting Corporation (CBC)', '21st Century Film Production', 'Temple Hill Productions', 'Home Box Office (HBO)', 'Jewson Film', 'Mate Producciones S.A.', 'David Hamilton Productions', 'Signature Pictures', 'Splendid Film', 'Oscilloscope Laboratories', 'Cliffjack Motion Pictures', 'Access Motion Picture Group', 'Bel Air Entertainment', '2929 Productions', 'Protozoa Pictures', 'Limb from Limb Pictures', 'Society Entertainment', 'Norman Twain Productions', 'Odyssey Entertainment', 'Fathom Studios', 'Midnight Sun Pictures', 'Artists Public Domain', 'Movision', 'Punch Productions', 'North by Northwest Entertainment', 'Mile High Productions', 'Wildgaze Films', 'Cruise/Wagner Productions', 'Phantom Four', 'The Guber-Peters Company', 'Granada Film Productions', 'Thinkfilm', 'Ikiru Films', 'New Century Entertainment Corporation', 'Bazmark Films', 'Warner Bros. Pictures', 'Media Asia Films', 'Wild Bunch', 'Bungalow Productions', 'Movieworld Productions', 'UK Film Council', 'HighRoad Entertainment', 'Greenestreet Films', 'Adlabs Films Ltd.', 'Dino De Laurentiis Company', 'The Combine', 'Applause Pictures', 'Triple D Productions', 'Robson Street', 'Cineplex-Odeon Films', 'Blue Dot Productions', 'Walt Disney Productions', 'Mutual Film Company', 'Alcon Entertainment', 'Tim Burton Animation Company', 'Mirage Enterprises', 'One Race Films', 'Apipoulaï', 'Waverly Films', 'Channel Four Films', 'Buena Vista', 'The Harold Greenberg Fund', 'Wonderworld Studios', 'Crossbow Productions', 'Darius Films', 'France 2 Cinéma', 'Anchor Bay Films', 'SBK Pictures', 'New World Pictures', 'Gold Lion Films', 'Polish Brothers Construction', 'Firm Films', 'Bright Cold Day Films', 'Figment Films', 'CBS Films', 'Star Overseas', 'South Pacific Pictures', 'This Is That Productions', 'Renaissance Films', 'Sunrise Films', 'One Race Productions', 'BBC', 'Cinergi Pictures Entertainment', 'Ozla Productions', 'Big Idea Productions', 'Quickfire Films', 'Lions Gate Films', 'Arsénico Producciones', 'Killer Films', 'Spy Global Media', 'The Poker House', 'Woodfall Film Productions', 'Rogue Pictures', 'United Artists Corporation', 'Miramax', 'TriStar Television', 'Nero Films', '34th Street Films', 'Brillstein-Grey Entertainment', 'BIM Distribuzione', 'New Artists Alliance', 'After Eden Pictures', 'Tollin/Robbins Productions', 'Bookshop Productions', 'El Deseo', 'McCreary Entertainment', 'Intandem Films', 'Lucasfilm', 'Walt deFaria', 'Lion Rock Productions', 'Global Creative Studios', 'BlinkWorks Media', 'Icon Entertainment International', 'Herold and Family', 'Starburns Industries', 'David Foster Productions', 'Centropolis Entertainment', 'BBC Films', 'Deviant Films', 'Asylum Films', 'Grindfest', 'Interscope Communications', 'Hyde Park Films', 'Dean River Productions', 'Detention Films', 'Broken Lizard Industries', 'Phillybrook Films', 'Emmett/Furla Films', 'Summit Entertainment', 'Tokuma Shoten', 'Seven Arts Productions', 'Aardman Animations', 'Current Entertainment', 'Infinity Omnimedia', 'October Films', 'New Regency Pictures', 'Autonomous', 'The Kushner-Locke Company', 'Everyman Pictures', 'Arts Council of England', 'Libido Cine', 'Immortal Thoughts', 'Goldcrest Pictures', 'Kopelson Entertainment', 'HDNet Films', 'Camphor Cinema', 'Boll KG', 'Tandem Pictures', 'Walt Disney Animation Studios', 'ARTE', 'X-Filme Creative Pool', 'ESX Productions', 'Honora Productions', 'Pacific Data Images (PDI)', 'Larger Than Life Productions', 'SuperMassive Films', 'Impact Productions LLC', 'Filmacres', 'Garden Thieves Pictures', 'Fragmighty', 'Artfire Films', 'Shadowlight Productions', 'Decipher Entertainment', 'Toei Animation Company', 'IFC Films', 'Front Street Pictures', 'Davis-Films', 'Arachnid Productions Ltd.', 'Estudios Picasso', 'Fandango', 'September Dawn', 'Rainforest Films', 'Weintraub Entertainment Group', 'Hemisphere Pictures', 'Electric Entertainment', 'Centropolis Film Productions', 'Lightning Entertainment', 'Company Pictures', 'Taodue Film', 'Toho Company', 'Millenium Films', 'Les Films 21', 'Michael London Productions', 'Cine Bazar', 'Aldamisa Entertainment', 'Australian Film Finance Corporation (AFFC)', 'Warner Bros.', 'Hanmac Films', 'Elevation Filmworks', 'Warner Bros. Animation', 'Les Productions du Trésor', 'TADORA Filmproduktions', 'CoBo Fund', 'Pure Flix Productions', 'Troma Entertainment', 'A Loopy Production LLC', 'Minds Eye Entertainment', 'Constantin Film', 'American Zoetrope', 'Parallel Pictures', 'T.H.E. Films', 'Nimbus Film Productions', 'Entertainment One Pvt. Ltd.', 'Bad Robot', "Forest Whitaker's Significant Productions", 'Rook Films', 'Starz Animation', 'Cinema Vehicle Services', 'Playtone', 'Paramount Pictures', 'Steel Mill Pictures', 'Walt Disney', 'Vertigo Entertainment', 'Brooksfilms Ltd.', 'Fidélité Productions', 'Merchant Films', 'Twentieth Century Fox Film Corporation', 'Flicks Motion Pictures', 'DuArt Film and Video', 'Cambridge Productions', 'Lions Gate Television', 'Concert Promotion International', 'Great Scott Productions Pty. Ltd.', 'CN Film', 'Producers Sales Organization', 'Big Indie Pictures', 'Filmula', 'Arte', 'Touchstone Pictures', 'Hopscotch Features', 'Virgin Produced', 'FM Productions', 'Park Films', 'Guerilla High Productions', 'Brave New Films', 'Eclectic pictures', 'Walden Media', 'Darko Entertainment', 'Original Pictures', 'Max TV', 'Tapestry Films', 'Ruby in Paradise', 'The New Zealand Film Commission', 'Phoenix Pictures', '1818', 'Warp X', 'The Montecito Picture Company', 'CJ Entertainment', 'Det Danske Filminstitut', 'Pariah Entertainment Group', 'Samuel Goldwyn', 'Hobby Films', 'Regency Enterprises', 'WingNut Films', 'Brooksfilms', 'First Independent Pictures', 'Samuel Goldwyn Films', 'Before the Door Pictures', 'Jersey Films', 'Velvet Steamroller Entertainment', 'Votiv Films', 'Kintop Pictures', 'Blueprint Pictures', 'Mirabai Films', 'Cinematograph AB', 'British Broadcasting Corporation (BBC)', 'Parts and Labor', 'FOTP Productions', 'Nordic Film', 'A Band Apart', 'Hideaway Pictures', 'Allure Entertainment', 'Art Linson Productions', 'Kirghizfilm', 'Screen Gems, Inc.', 'China Film Group Corporation', 'Falcon International Productions', 'Claussen + Wöbke Filmproduktion GmbH', '3L Filmproduktion GmbH', 'Pathé Pictures International', 'Acajou Films', 'Birdsong Pictures', 'Canal Plus', 'Likely Story', 'Vnesheconombank', 'Yash Raj Films', 'Animus Films', 'Haut et Court', 'AVCO Embassy Pictures', 'Caliber Media Company', 'John Wells Productions', 'New Sky Communications Inc.', 'Thousand Words', 'Baleuko S.L.', 'Davis-Panzer Productions', 'Selznick International Pictures', 'Gerber Pictures', 'ContentFilm', "Donners' Company", 'Crest Animation Production', 'New Zealand Film Commission', 'Quincy Jones-David Salzman Entertainment', 'CJ Capital Investment', 'Hartbreak Films', 'Park Ex Pictures', 'Freestyle Releasing', 'JCE Movies', 'Cracking the Earth Films', 'Arcade Pictures', 'Unstuck', 'Plunge Pictures LLC', 'Studio Babelsberg', 'Big Talk Productions', 'Omnilab Media', 'Edward Small Productions', 'Dharma Productions', 'Matador Pictures', 'Lenfilm Studio', 'Furst Films', '3 Arts Entertainment', 'Marvel Studios', 'Silver Screen Partners II', 'Eskwad', 'Film Science', "Baker's Dozen Productions", 'Wendy Finerman Productions', 'Shaw Brothers', 'Comedy Central Films', 'Focus Films', 'Cappa Productions', 'Heavy Duty Entertainment', 'Eyeline Entertainment', 'Tribeca Film', 'Institution, The', 'Redeemable Features', 'Snoot Entertainment', 'Kennedy Miller Productions', 'Iyara Films', 'Hi-Rez Films', 'Dune Entertainment', 'Skyscraper Films', 'Onyx Films', 'Embassy International Pictures', 'Saturn Films', 'Euro International Film (EIA)', 'Team Todd', 'Kaos Entertainment', 'Danmarks Radio (DR)', 'Gravier Productions', 'Gold/Miller Productions', 'Hofflund/Polone', 'Ixtlan Productions', 'Irish Dreamtime', 'Plum Pictures', 'Pathe Productions', 'Bill Plympton Studios', 'Rigel Entertainment', 'Cohen Media Group', 'Block 2 Pictures', 'Trans Pacific Films', 'Marathon Pictures', 'Laundry Films', 'Paramount Vantage', 'Beijing New Picture Film Co. Ltd.', 'Capitol Films', 'Producers Circle', 'Walt Disney Television Animation', '360 Pictures', 'Rollins-Joffe Productions', 'Weinstein Company, The', 'Lions Gate Family Entertainment', 'American Film Institute (AFI)', 'Status Media & Entertainment', 'Relativity Media', 'American Filmworks', 'RabbitBandini Productions', 'NAZZ Productions', 'Stone Productions', 'Act III Communications', 'Strand Releasing', 'Stanley Kubrick Productions', 'Fox 2000 Pictures', 'Darlow Smithson Productions', 'Rival Pictures', 'New Line Productions', 'Les Films du Poisson', 'Sneak Preview Productions', 'NeeNee Productions', 'Myriad Pictures', 'Scottish Screen', 'Yari Film Group', 'TriStar Pictures', 'SLM Production Group', 'Escape Artists', 'Film Department, The', 'GraceWorks Pictures', 'Iconoclast Films', 'Metropolitan Filmexport', 'PSO International', 'TinRes Entertainment', 'Magidson Films', 'Bórd Scannán na hÉireann', 'Cherry On Top', 'Insurge Pictures', 'DiNovi Pictures', 'Lightstorm Entertainment', 'Asymmetrical Productions', 'Journeyman Pictures', 'Film Council', 'Lucky Monkey Pictures', 'Neal Street Productions', 'Head Gear Films', "Les Films d'Ici", 'Red Om Films', 'AV Pictures', 'Rainbow Film Company, The', 'Anonymous Content', 'Echo Lake Productions', 'Darclight', 'Hartbeat Productions', 'Smokewood Entertainment Group', 'Detour Film Production', '3rd Partner Productions', 'SND', 'Orsay Films', 'Dimension Films', 'Mpower Pictures', 'Pictures in Paradise', 'Partition Films%2C Inc.', 'Gold Circle Films', 'Allied Artists Pictures', 'Spring Films', 'Nordisk Film', 'Universal', 'Film 4', 'Rigas Entertainment', 'Saga Film', 'Industry Entertainment', 'Envision Media Arts', 'Woods Entertainment', 'Independence Day Productions', 'Will Packer Productions', 'Milagro Films', 'Icon Productions', 'Young Medium', 'Entertainment Films', 'Filmko Pictures', 'New Kingdom Pictures', 'Nic Arts', 'Copperheart Entertainment', 'Kathbur Pictures', 'Tax Credit Finance', 'The Zanuck Company', 'City Light Films', 'Oops Doughnuts Productions', 'Bac Films', 'Battleplan Productions', 'Sony Pictures', 'Mockingbird Pictures', 'Infinitum Nihil', 'Anarchos Productions', 'Back Lot Pictures', 'Epithète Films', 'Cheyenne Enterprises', 'Nickelodeon Movies', 'Patalex IV Productions Limited', 'Huayi Brothers', 'Metro-Goldwyn-Mayer (MGM)', 'Mandarin Films Distribution Co.', 'Filmhuset Gruppen', 'Charles K. Feldman Group', 'La Fabrique de Films', 'Chromewood Productions', 'Mark Johnson Productions', 'Metanoia Films', 'Tiger Tail Entertainment', 'Next Wednesday Productions', 'Corona Pictures', 'Arrowstorm Entertainment', 'Bazelevs Production', 'Rising Star', 'Ealing Studios', 'Virtual Studios', 'Automatik Entertainment', 'Senator Entertainment Co', "Anarchist's Convention Films", 'Rapid Heart Pictures', 'Belstar Productions', 'Absinthe Productions', 'De Line Pictures', 'MGM', 'Annuit Coeptis Entertainment Inc.', 'Red Cube Picture', 'JVC Entertainment', 'Hawk Films', 'Portman Entertainment Group', 'Lietuvos Kinostudija', 'Estudios Churubusco Azteca', 'Screen Australia', 'Team Awesome Films', 'Egg Pictures', 'Gotham Group', 'Bleiberg Entertainment', 'Geffen Company, The', 'Cannon Films', 'River Road Entertainment', 'A Space Between', 'Palladium Film', 'Wells & Jeta Entertainment', 'Bedford Falls Productions', 'Revolution Studios', 'MTV Films', 'Summit Entertainment, LLC', 'Famous Films (II)', 'Emperor Motion Pictures', 'Arcadia Motion Pictures', 'Ingenious Film Partners', 'Wessler Entertainment', 'Tremolo Productions', 'Dead Films', 'Futurikon', 'Miramax Films', 'Scott Rudin Productions', 'Worldview Entertainment', 'Westerly Films', 'Calder Road Film', 'Prospect Pictures', 'Initial Entertainment Group (IEG)', 'Medusa Produzione', 'Eon Productions', 'Vanguard Films', 'DNA Films', 'Double Feature Films', 'Lakeshore Entertainment', 'Endgame Entertainment', 'Blue Askew', 'Grand Army Entertainment', 'Pantelion Film', 'Occupant Films', 'The Picture Factory', 'Prophecy Pictures Ltd.', 'Franchise Pictures', 'RKO Radio Pictures', 'Ruckus Films', 'Ad Hominem Enterprises', 'T-Series', 'Indian Paintbrush', 'Cannon Group', 'Sundial Pictures', 'Showtime Australia', 'Lions Gate', 'WDR', 'Fountainbridge Films', 'Hammer Film Productions', 'Savoy Pictures', 'Ponty Up Pictures', 'Henry & Me Productions', 'National Geographic Entertainment', 'Numb Gums Production Inc.', 'A Bigger Boat', 'Tag Entertainment', 'Atlantic Entertainment Group', 'Mandate Pictures', 'Hunting Lane Films', 'Feature Film Project', 'Kennedy/Marshall Company, The', 'Verisimilitude', 'Red-horse Native', 'Columbia Pictures', 'The Rank Organisation', 'NGN Productions', 'Dalia Films', 'Fulvia Film', 'Cinema 77', 'ANA Media', 'GF Studios AB', 'United Artists', 'Scott Free Productions', 'Code Productions', 'Ignite Entertainment', 'Corsan', 'Keith Barish Productions', 'Solaris Film', 'Daniel Columbie Films & Productions', 'Film Threat DVD', 'Clinica Estetico', 'Maipo Film- og TV Produksjon', 'Against the Wild Films', 'Youth House Productions', 'Magnolia Pictures', 'Associated General Films', 'Kasdan Pictures', 'Yeah', 'British Film Institute (BFI)', 'Open Road Films (II)', 'Irish Film Board', 'Counterclock Productions', 'ITC Entertainment', 'First Floor Features', 'Hemdale Film Corporation', 'The Jacobson Company', 'Hazeldine Films', 'Steamroller Productions', 'Appian Way', 'Sidney Kimmel Entertainment', 'Amen Ra Films', 'Silver Screen Partners III', 'Samuel Goldwyn Company, The', 'Motion Picture Corporation of America', 'Celador Films', 'Toho Film (Eiga) Co. Ltd.', 'The Kennedy/Marshall Company', 'Illumination Pictures', 'Prana Animation Studios', 'Rockaway the Movie', 'LeVision Pictures', 'Agi Orsi Productions', 'Hollywood Pictures', 'L.I.F.T. Production', 'Incorporated Television Company', 'Merchant Ivory Productions', 'Grand Peaks Entertainment', 'Village Roadshow Pictures', 'Intrepid Pictures', 'Hydraulx', 'Himenóptero', 'Vertigo Productions', 'The Asylum', 'Pegasus Motion Pictures', 'Palpable Productions', 'Universal Pictures Corporation', 'The Javelina Film Company', 'Front Street Productions', 'Legendary Pictures', 'Desilu Productions', 'Film4', 'SC Films International', 'Open Road Films', 'Eden Rock Media', 'Invincible Pictures Corp.', 'Incentive Filmed Entertainment', 'Conundrum Entertainment', 'Bollywood Hollywood Production', 'IDG China Media', 'Liberty Films UK', 'Archer Street Productions', 'Lord of the Wind', 'Par-Par Productions', 'Depth of Field', 'Suntaur Entertainment Company', 'Hubert Bals Fund', 'Les Films du Carrosse', 'Why Not Productions', 'Alliance Films', 'Walt Disney Studios Motion Pictures', 'Voltage Pictures', 'Upload Films', 'WWE Studios', 'Eivissa Productions', 'Reeleyes Film', 'Constellation Films', '30 Something Productions', 'Karz Entertainment', 'Cinémaginaire Inc.', 'Pandora Filmproduktion', 'Celluloid Dreams', 'Golden Harvest Company', 'Clear Blue Sky Productions', 'Ombra Films', 'Carousel Picture Company', 'Perfo Production', 'Shanghai Film Group', 'Warner Brothers/Seven Arts', 'Polonia Brothers Entertainment', 'Alex Entertainment Inc.', 'N3D Land Productions', 'Whitewater Films', 'Reiner / Greisman Productions', 'Konrad Pictures', 'Studio 18', 'Gullane Entretenimento S.A.', 'GO Productions', 'The Weinstein Company', 'Teeth', 'Cookout Productions', 'David LaChapelle Studios', 'Razor Film Produktion GmbH', 'Antares Produzione Cinematografica', 'Centre National de la Cinématographie', 'DC Comics', 'Variance Films', 'BBC Worldwide', 'Jafar Panahi Film Productions', 'The Mark Gordon Company', 'Gracie Films', 'Laura Ziskin Productions', 'R&C Produzioni', 'Golden Mean', 'Camelot Productions', 'Tiger Aspect Productions', 'Muse Productions', 'O Entertainment', 'Grindstone Entertainment Group', 'Media Rights Capital', 'SNL Studios', 'Infinity Features Entertainment', 'Cannon Pictures', 'Vertigo Films', 'Identity Films', 'Arka Media Works', 'Les Films Alain Sarde', 'Brightlight Pictures', 'Limited Edition Productions Inc.', 'Vulcan Productions Inc.', 'Egoli Tossell Film AG', 'Egg Films', 'FlipZide Pictures', 'Evenstar Films', 'XYZ Films', 'Working Title Films', 'Parker Film Company', 'Fox Atomic', 'Coração da Selva', 'Gran Via Productions', 'Qwerty Films', 'First Choice Films', 'Extension 765', 'Octagon Films', 'Studio Ghibli', 'Overseas FilmGroup', 'Skyline Films', 'Two Camels Films', 'Trilogy Entertainment Group', '26 Films', 'Lawrence Bender Productions', 'Joanna Productions', 'Duplass Brothers Productions', 'George Stevens Productions', 'Canadian Film Development Corporation (CFDC)', 'Blue Trail Entertainment', 'Ghoulardi Film Company', 'Sweetland Films', 'Radiant Film GmbH', 'Fragile Films', 'Neo Art & Logic', 'Mad Chance', 'Téléfilm Canada', 'Entertainment', 'Room 101', 'Mantarraya Producciones', 'David Brown Productions', 'Bentley Filmgroup', 'MTM Cineteve', 'Parkwood Entertainment', 'Timnick Films', 'Roast Beef Productions', 'Columbia Pictures Corporation', 'M6 Films', 'O2 Filmes', 'August Heart Entertainment', 'Grosvenor Park Films LLP', '21 Laps Entertainment', 'SKA Films', 'Apostle Productions', 'Parallel Films', 'Tig Productions', 'Respect Films', 'Walt Disney Pictures', 'Scala Films', 'Constantin Film Produktion', 'No Limit Films', 'Cobalt Media Group', 'Reel FX Creative Studios', 'Triangle Film Corporation', 'Beacon Communications', 'IMAX', 'Ultra Films', 'Les Films Alyne', 'Burn Later Productions', 'Tre Vänner Produktion AB', 'Greek Film Center', 'Perdido Productions', 'New South Wales Film & Television Office', 'Pathé Films', 'Two Streets Entertainment', 'Strike Entertainment', 'Ingenious Media', 'HandMade Films', 'MGM Television', 'Les Productions Artistes Associés', 'Quality Films Entertainment', 'Rastar Pictures', 'Phase 4 Films', 'Filmkameratene A/S', 'Rai Cinema', 'Cineclick Asia', 'JoBro Productions & Film Finance', 'Gramercy Pictures', 'Kalkaska Productions', 'Caravan Pictures', 'Silver Screen Partners', 'Pandora Cinema', 'Les Films du Jeudi', 'Northern Lights Films', 'Mosaic Media Group', 'Becker International', 'Mid Atlan

In [22]:
X = film.select_dtypes(include=[object])
X.head(5)

,genres,production_companies,production_countries,spoken_languages,status
0,Action,Ingenious Film Partners,United States of America,English,Released
1,Adventure,Walt Disney Pictures,United States of America,English,Released
2,Action,Columbia Pictures,United Kingdom,Français,Released
3,Action,Legendary Pictures,United States of America,English,Released
4,Action,Walt Disney Pictures,United States of America,English,Released

In [23]:
X.shape

(4803, 5)

In [24]:
X.columns

Index(['genres', 'production_companies', 'production_countries',
       'spoken_languages', 'status'],
      dtype='object')

In [25]:
# values = array(X['genres'])
le = preprocessing.LabelEncoder()
X_2 = X.apply(le.fit_transform)
X_2.head()

,genres,production_companies,production_countries,spoken_languages,status
0,0,611,70,8,1
1,1,1258,70,8,1
2,0,262,69,11,1
3,0,691,70,8,1
4,0,1258,70,8,1

In [26]:
onehot_encoder = preprocessing.OneHotEncoder()
onehot_encoder.fit(X_2)

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [27]:
X_2.head(5)

,genres,production_companies,production_countries,spoken_languages,status
0,0,611,70,8,1
1,1,1258,70,8,1
2,0,262,69,11,1
3,0,691,70,8,1
4,0,1258,70,8,1

In [28]:
X_2.shape

(4803, 5)

In [29]:
film['genres'] = X_2['genres']
film['production_companies'] = X_2['production_companies']
film['production_countries'] = X_2['production_countries']
film['spoken_languages'] = X_2['spoken_languages']
film['status'] = X_2['status']

In [30]:
film.head()

,budget,genres,id,popularity,production_companies,production_countries,revenue,runtime,spoken_languages,status,vote_average,vote_count
0,237000000,0,19995,150.437577,611,70,2787965087,162.0,8,1,7.2,11800
1,300000000,1,285,139.082615,1258,70,961000000,169.0,8,1,6.9,4500
2,245000000,0,206647,107.376788,262,69,880674609,148.0,11,1,6.3,4466
3,250000000,0,49026,112.312950,691,70,1084939099,165.0,8,1,7.6,9106
4,260000000,0,49529,43.926995,1258,70,284139100,132.0,8,1,6.1,2124

In [31]:
film.corr(method='spearman')

,budget,genres,id,popularity,production_companies,production_countries,revenue,runtime,spoken_languages,status,vote_average,vote_count
budget,1.000000,-0.221049,-0.246105,0.649466,0.107306,0.099395,0.756841,0.326022,-0.080378,-0.018119,0.066183,0.663368
genres,-0.221049,1.000000,0.092425,-0.105318,-0.058555,-0.023148,-0.149322,0.004913,0.029136,-0.017735,0.053994,-0.112042
id,-0.246105,0.092425,1.000000,-0.277905,-0.047529,-0.040808,-0.292255,-0.215205,0.072226,0.000623,-0.266219,-0.296946
popularity,0.649466,-0.105318,-0.277905,1.000000,0.086005,0.098666,0.776679,0.301983,-0.094036,-0.020820,0.359288,0.959807
production_companies,0.107306,-0.058555,-0.047529,0.086005,1.000000,0.044058,0.135790,0.026871,-0.031831,-0.000776,0.003614,0.084087
production_countries,0.099395,-0.023148,-0.040808,0.098666,0.044058,1.000000,0.145376,-0.047940,-0.179606,-0.009295,-0.039665,0.106133
revenue,0.756841,-0.149322,-0.292255,0.776679,0.135790,0.145376,1.000000,0.317012,-0.084466,-0.015924,0.243457,0.804056
runtime,0.326022,0.004913,-0.215205,0.301983,0.026871,-0.047940,0.317012,1.000000,0.000596,-0.011518,0.397664,0.303825
spoken_languages,-0.080378,0.029136,0.072226,-0.094036,-0.031831,-0.179606,-0.084466,0.000596,1.000000,0.025033,0.017784,-0.092714
status,-0.018119,-0.017735,0.000623,-0.020820,-0.000776,-0.009295,-0.015924,-0.011518,0.025033,1.000000,0.000521,-0.021104
vote_average,0.066183,0.053994,-0.266219,0.359288,0.003614,-0.039665,0.243457,0.397664,0.017784,0.000521,1.000000,0.381283
vote_count,0.663368,-0.112042,-0.296946,0.959807,0.084087,0.106133,0.804056,0.303825,-0.092714,-0.021104,0.381283,1.000000

### Data Splitting

In [38]:
film_cols = film.columns
train_cols = [x for x in film_cols if x != 'revenue']

X = film[train_cols]
y = film['revenue']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=91, test_size=0.3,
)

### Decision Tree Regression

In [55]:
dt_reg = DecisionTreeRegressor(max_depth=2)
dt_reg.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=2, max_features=None,
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

In [56]:
y_pred = dt_reg.predict(X_test)
mse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print("MSE: ", mse)

MSE:  103251727.944

### Linear Regression

In [57]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [58]:
y_pred = lin_reg.predict(X_test)
# mse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
# print("MSE: ", mse)

# The coefficients
print('Coefficients: \n', lin_reg.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))

# Plot outputs
plt.scatter(X_test, diabetes_y_test,  color='black')
plt.plot(X_test, diabetes_y_pred, color='blue', linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()

MSE:  87742086.7412

### Logistic Regression

In [59]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [60]:
y_pred = log_reg.predict(X_test)
mse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print("MSE: ", mse)

MSE:  174187643.533

### Decision Tree Classification

In [50]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [49]:
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)*100
print("Akurasi: ", accuracy,"%")

Akurasi:  18.66759195 %

In [36]:
confusion_matrix(y_test, y_pred)

array([[272,   0,   0, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]])